spring.application.name=medical_Clinic
spring.profiles.active=test
spring.jpa.open-in-view=true 
spring.config.import=optional:file:.env[.properties]
jwt.secret=${JWT_SECRET:61a71eb6c959195950aa5dd28cbb825333f4306ea8c94d772a0256f9b9cc20a9}
logging.level.org.springframework.security=DEBUG